#server:
#  port: 8083
#
#file:
#  upload-dir: ./uploads
#
#jwt:
#  secret: "enadzornikSuperSecureSecretKey32CharsMin!"
#
#logging:
#  level:
#    rs.enadzornik: DEBUG

server:
  port: 8085

spring:
  application:
    name: auth-service
  datasource:
    url: jdbc:mysql://localhost:3306/enadzornik?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
    username: enadzornik
    password: enadzornik
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
  web:
    cors:
      allowed-origins: "*"
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB
logging:
  level:
    rs.enadzornik: DEBUG
file:
  upload-dir: ./uploads