# evaluation-service/src/main/resources/application.yml
server:
  port: 8087

spring:
  application:
    name: audit-service
  datasource:
    url: jdbc:mysql://localhost:3306/enadzornik?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
    username: enadzornik
    password: enadzornik
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
  web:
    cors:
      allowed-origins: "*"
# URL ka material-service (za a≈æuriranje statusa)
material-service:
  url: http://material-service:8084

logging:
  level:
    rs.enadzornik.evaluationservice: DEBUG